/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_gestioncitoyen (void)
{
  GtkWidget *gestioncitoyen;
  GtkWidget *notebook1;
  GtkWidget *fixed4;
  GtkWidget *buttonmodif;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image15;
  GtkWidget *label56;
  GtkWidget *buttonsupprimer;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image16;
  GtkWidget *label57;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeviewcitoyenA;
  GtkWidget *entryrecherchehome;
  GtkWidget *recherchehome;
  GtkWidget *image18;
  GtkWidget *buttonRafraichir;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image17;
  GtkWidget *label58;
  GtkWidget *labelAfficher;
  GtkWidget *fixed8;
  GtkWidget *entryNomA;
  GtkWidget *entryPrenomA;
  GtkObject *spinbuttonJourA_adj;
  GtkWidget *spinbuttonJourA;
  GtkObject *spinbuttonAnneeA_adj;
  GtkWidget *spinbuttonAnneeA;
  GtkWidget *entryVilleA;
  GtkWidget *entryEmailA;
  GtkWidget *entryCINA;
  GtkWidget *entryTelephoneA;
  GtkWidget *labelPrenomA;
  GtkWidget *buttonAjouter;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image7;
  GtkWidget *label;
  GtkWidget *labelEmailA;
  GtkWidget *labelTelephoneA;
  GtkWidget *labelVilleA;
  GtkWidget *labelSexeA;
  GtkWidget *labelDatenaissanceA;
  GtkWidget *radioHommeA;
  GSList *radioHommeA_group = NULL;
  GtkWidget *combobox1;
  GtkWidget *radioFemmeA;
  GtkWidget *labelNomA;
  GtkWidget *labelCINA;
  GtkWidget *checkbutton1;
  GtkWidget *labelAjouter;
  GtkWidget *fixed6;
  GtkWidget *entryNommodif;
  GtkWidget *entryPrenommodif;
  GtkObject *spinbuttonJourmodif_adj;
  GtkWidget *spinbuttonJourmodif;
  GtkWidget *entryEmailmodif;
  GtkWidget *entryCINmodif;
  GtkWidget *entryTelephonemodif;
  GtkWidget *entryVillemodif;
  GtkObject *spinbuttonAnneemodif_adj;
  GtkWidget *spinbuttonAnneemodif;
  GtkWidget *labelPrenommodif;
  GtkWidget *labelNommodif;
  GtkWidget *labelCINconf;
  GtkWidget *buttonModifier;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image12;
  GtkWidget *label52;
  GtkWidget *labelDatenaissancemodif;
  GtkWidget *labelSexemodif;
  GtkWidget *radiobuttonHommemodif;
  GSList *radiobuttonHommemodif_group = NULL;
  GtkWidget *combobox2;
  GtkWidget *radiobuttonFemmemodif;
  GtkWidget *labelEmailmodif;
  GtkWidget *labelTelephonemodif;
  GtkWidget *labelVillemodif;
  GtkWidget *checkbutton2;
  GtkWidget *labelModifier;
  GtkWidget *fixed5;
  GtkWidget *treeviewcitoyenC;
  GtkWidget *entryCINC;
  GtkObject *spinbuttonMoisC_adj;
  GtkWidget *spinbuttonMoisC;
  GtkWidget *label59;
  GtkWidget *labelCINC;
  GtkWidget *label60;
  GtkWidget *label61;
  GtkWidget *buttonImprimer;
  GtkWidget *combobox3;
  GtkWidget *labelcalculer;

  gestioncitoyen = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gestioncitoyen), _("gestioncitoyen"));

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (gestioncitoyen), notebook1);
  gtk_container_set_border_width (GTK_CONTAINER (notebook1), 6);
  gtk_notebook_set_scrollable (GTK_NOTEBOOK (notebook1), TRUE);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  buttonmodif = gtk_button_new ();
  gtk_widget_show (buttonmodif);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonmodif, 168, 312);
  gtk_widget_set_size_request (buttonmodif, 96, 32);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (buttonmodif), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image15 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox9), image15, FALSE, FALSE, 0);

  label56 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label56);
  gtk_box_pack_start (GTK_BOX (hbox9), label56, FALSE, FALSE, 0);

  buttonsupprimer = gtk_button_new ();
  gtk_widget_show (buttonsupprimer);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonsupprimer, 336, 312);
  gtk_widget_set_size_request (buttonsupprimer, 96, 32);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (buttonsupprimer), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image16 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox10), image16, FALSE, FALSE, 0);

  label57 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label57);
  gtk_box_pack_start (GTK_BOX (hbox10), label57, FALSE, FALSE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed4), scrolledwindow1, 24, 64);
  gtk_widget_set_size_request (scrolledwindow1, 848, 240);

  treeviewcitoyenA = gtk_tree_view_new ();
  gtk_widget_show (treeviewcitoyenA);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeviewcitoyenA);
  gtk_widget_set_size_request (treeviewcitoyenA, 880, 184);

  entryrecherchehome = gtk_entry_new ();
  gtk_widget_show (entryrecherchehome);
  gtk_fixed_put (GTK_FIXED (fixed4), entryrecherchehome, 616, 32);
  gtk_widget_set_size_request (entryrecherchehome, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryrecherchehome), 8226);

  recherchehome = gtk_button_new ();
  gtk_widget_show (recherchehome);
  gtk_fixed_put (GTK_FIXED (fixed4), recherchehome, 800, 32);
  gtk_widget_set_size_request (recherchehome, 66, 29);

  image18 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_container_add (GTK_CONTAINER (recherchehome), image18);

  buttonRafraichir = gtk_button_new ();
  gtk_widget_show (buttonRafraichir);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonRafraichir, 488, 312);
  gtk_widget_set_size_request (buttonRafraichir, 96, 32);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (buttonRafraichir), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image17 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox11), image17, FALSE, FALSE, 0);

  label58 = gtk_label_new_with_mnemonic (_("Rafraichir"));
  gtk_widget_show (label58);
  gtk_box_pack_start (GTK_BOX (hbox11), label58, FALSE, FALSE, 0);

  labelAfficher = gtk_label_new (_("Afficher"));
  gtk_widget_show (labelAfficher);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), labelAfficher);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed8);

  entryNomA = gtk_entry_new ();
  gtk_widget_show (entryNomA);
  gtk_fixed_put (GTK_FIXED (fixed8), entryNomA, 192, 40);
  gtk_widget_set_size_request (entryNomA, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNomA), 8226);

  entryPrenomA = gtk_entry_new ();
  gtk_widget_show (entryPrenomA);
  gtk_fixed_put (GTK_FIXED (fixed8), entryPrenomA, 192, 80);
  gtk_widget_set_size_request (entryPrenomA, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryPrenomA), 8226);

  spinbuttonJourA_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonJourA = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonJourA_adj), 1, 0);
  gtk_widget_show (spinbuttonJourA);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbuttonJourA, 168, 128);
  gtk_widget_set_size_request (spinbuttonJourA, 60, 27);

  spinbuttonAnneeA_adj = gtk_adjustment_new (2024, 1900, 2025, 1, 10, 10);
  spinbuttonAnneeA = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonAnneeA_adj), 1, 0);
  gtk_widget_show (spinbuttonAnneeA);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbuttonAnneeA, 384, 128);
  gtk_widget_set_size_request (spinbuttonAnneeA, 60, 27);

  entryVilleA = gtk_entry_new ();
  gtk_widget_show (entryVilleA);
  gtk_fixed_put (GTK_FIXED (fixed8), entryVilleA, 184, 272);
  gtk_widget_set_size_request (entryVilleA, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryVilleA), 8226);

  entryEmailA = gtk_entry_new ();
  gtk_widget_show (entryEmailA);
  gtk_fixed_put (GTK_FIXED (fixed8), entryEmailA, 184, 200);
  gtk_widget_set_size_request (entryEmailA, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryEmailA), 8226);

  entryCINA = gtk_entry_new ();
  gtk_widget_show (entryCINA);
  gtk_fixed_put (GTK_FIXED (fixed8), entryCINA, 192, 8);
  gtk_widget_set_size_request (entryCINA, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryCINA), 8226);

  entryTelephoneA = gtk_entry_new ();
  gtk_widget_show (entryTelephoneA);
  gtk_fixed_put (GTK_FIXED (fixed8), entryTelephoneA, 184, 232);
  gtk_widget_set_size_request (entryTelephoneA, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryTelephoneA), 8226);

  labelPrenomA = gtk_label_new (_("Prenom :"));
  gtk_widget_show (labelPrenomA);
  gtk_fixed_put (GTK_FIXED (fixed8), labelPrenomA, 32, 80);
  gtk_widget_set_size_request (labelPrenomA, 72, 16);

  buttonAjouter = gtk_button_new ();
  gtk_widget_show (buttonAjouter);
  gtk_fixed_put (GTK_FIXED (fixed8), buttonAjouter, 184, 360);
  gtk_widget_set_size_request (buttonAjouter, 96, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (buttonAjouter), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image7 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox1), image7, FALSE, FALSE, 0);

  label = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label);
  gtk_box_pack_start (GTK_BOX (hbox1), label, FALSE, FALSE, 0);

  labelEmailA = gtk_label_new (_("Email :"));
  gtk_widget_show (labelEmailA);
  gtk_fixed_put (GTK_FIXED (fixed8), labelEmailA, 40, 208);
  gtk_widget_set_size_request (labelEmailA, 49, 17);

  labelTelephoneA = gtk_label_new (_("Telephone :"));
  gtk_widget_show (labelTelephoneA);
  gtk_fixed_put (GTK_FIXED (fixed8), labelTelephoneA, 24, 240);
  gtk_widget_set_size_request (labelTelephoneA, 96, 16);

  labelVilleA = gtk_label_new (_("mot de passe  :"));
  gtk_widget_show (labelVilleA);
  gtk_fixed_put (GTK_FIXED (fixed8), labelVilleA, 16, 272);
  gtk_widget_set_size_request (labelVilleA, 136, 24);

  labelSexeA = gtk_label_new (_("Sexe :"));
  gtk_widget_show (labelSexeA);
  gtk_fixed_put (GTK_FIXED (fixed8), labelSexeA, 32, 168);
  gtk_widget_set_size_request (labelSexeA, 64, 16);

  labelDatenaissanceA = gtk_label_new (_("Date de naissance :"));
  gtk_widget_show (labelDatenaissanceA);
  gtk_fixed_put (GTK_FIXED (fixed8), labelDatenaissanceA, 24, 128);
  gtk_widget_set_size_request (labelDatenaissanceA, 136, 16);

  radioHommeA = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radioHommeA);
  gtk_fixed_put (GTK_FIXED (fixed8), radioHommeA, 184, 176);
  gtk_widget_set_size_request (radioHommeA, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radioHommeA), radioHommeA_group);
  radioHommeA_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radioHommeA));

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed8), combobox1, 248, 128);
  gtk_widget_set_size_request (combobox1, 120, 32);
  gtk_container_set_border_width (GTK_CONTAINER (combobox1), 1);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Janvier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("F\303\251vrier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Mars"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Avril"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Mai"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Juin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Juillet"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Ao\303\273t"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Septembre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Octobre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Novembre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("D\303\251cembre"));

  radioFemmeA = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radioFemmeA);
  gtk_fixed_put (GTK_FIXED (fixed8), radioFemmeA, 312, 176);
  gtk_widget_set_size_request (radioFemmeA, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radioFemmeA), radioHommeA_group);
  radioHommeA_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radioFemmeA));

  labelNomA = gtk_label_new (_("Nom :"));
  gtk_widget_show (labelNomA);
  gtk_fixed_put (GTK_FIXED (fixed8), labelNomA, 40, 40);
  gtk_widget_set_size_request (labelNomA, 49, 17);

  labelCINA = gtk_label_new (_("CIN :"));
  gtk_widget_show (labelCINA);
  gtk_fixed_put (GTK_FIXED (fixed8), labelCINA, 40, 8);
  gtk_widget_set_size_request (labelCINA, 49, 17);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("j'accepte la politique de confidentialit\303\251"));
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed8), checkbutton1, 56, 320);
  gtk_widget_set_size_request (checkbutton1, 392, 32);

  labelAjouter = gtk_label_new (_("Ajouter"));
  gtk_widget_show (labelAjouter);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), labelAjouter);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed6);

  entryNommodif = gtk_entry_new ();
  gtk_widget_show (entryNommodif);
  gtk_fixed_put (GTK_FIXED (fixed6), entryNommodif, 168, 80);
  gtk_widget_set_size_request (entryNommodif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNommodif), 8226);

  entryPrenommodif = gtk_entry_new ();
  gtk_widget_show (entryPrenommodif);
  gtk_fixed_put (GTK_FIXED (fixed6), entryPrenommodif, 168, 112);
  gtk_widget_set_size_request (entryPrenommodif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryPrenommodif), 8226);

  spinbuttonJourmodif_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonJourmodif = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonJourmodif_adj), 1, 0);
  gtk_widget_show (spinbuttonJourmodif);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbuttonJourmodif, 168, 152);
  gtk_widget_set_size_request (spinbuttonJourmodif, 60, 27);

  entryEmailmodif = gtk_entry_new ();
  gtk_widget_show (entryEmailmodif);
  gtk_fixed_put (GTK_FIXED (fixed6), entryEmailmodif, 160, 232);
  gtk_widget_set_size_request (entryEmailmodif, 160, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryEmailmodif), 8226);

  entryCINmodif = gtk_entry_new ();
  gtk_widget_show (entryCINmodif);
  gtk_fixed_put (GTK_FIXED (fixed6), entryCINmodif, 168, 48);
  gtk_widget_set_size_request (entryCINmodif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryCINmodif), 8226);

  entryTelephonemodif = gtk_entry_new ();
  gtk_widget_show (entryTelephonemodif);
  gtk_fixed_put (GTK_FIXED (fixed6), entryTelephonemodif, 160, 264);
  gtk_widget_set_size_request (entryTelephonemodif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryTelephonemodif), 8226);

  entryVillemodif = gtk_entry_new ();
  gtk_widget_show (entryVillemodif);
  gtk_fixed_put (GTK_FIXED (fixed6), entryVillemodif, 160, 304);
  gtk_widget_set_size_request (entryVillemodif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryVillemodif), 8226);

  spinbuttonAnneemodif_adj = gtk_adjustment_new (2024, 1900, 2025, 1, 10, 10);
  spinbuttonAnneemodif = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonAnneemodif_adj), 1, 0);
  gtk_widget_show (spinbuttonAnneemodif);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbuttonAnneemodif, 384, 144);
  gtk_widget_set_size_request (spinbuttonAnneemodif, 60, 27);

  labelPrenommodif = gtk_label_new (_("Prenom :"));
  gtk_widget_show (labelPrenommodif);
  gtk_fixed_put (GTK_FIXED (fixed6), labelPrenommodif, 48, 120);
  gtk_widget_set_size_request (labelPrenommodif, 80, 16);

  labelNommodif = gtk_label_new (_("Nom :"));
  gtk_widget_show (labelNommodif);
  gtk_fixed_put (GTK_FIXED (fixed6), labelNommodif, 48, 88);
  gtk_widget_set_size_request (labelNommodif, 49, 17);

  labelCINconf = gtk_label_new (_("CIN :"));
  gtk_widget_show (labelCINconf);
  gtk_fixed_put (GTK_FIXED (fixed6), labelCINconf, 48, 56);
  gtk_widget_set_size_request (labelCINconf, 49, 17);

  buttonModifier = gtk_button_new ();
  gtk_widget_show (buttonModifier);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonModifier, 176, 376);
  gtk_widget_set_size_request (buttonModifier, 88, 32);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (buttonModifier), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image12 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox6), image12, FALSE, FALSE, 0);

  label52 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label52);
  gtk_box_pack_start (GTK_BOX (hbox6), label52, FALSE, FALSE, 0);

  labelDatenaissancemodif = gtk_label_new (_("Date de naissance :"));
  gtk_widget_show (labelDatenaissancemodif);
  gtk_fixed_put (GTK_FIXED (fixed6), labelDatenaissancemodif, 16, 152);
  gtk_widget_set_size_request (labelDatenaissancemodif, 128, 16);

  labelSexemodif = gtk_label_new (_("Sexe :"));
  gtk_widget_show (labelSexemodif);
  gtk_fixed_put (GTK_FIXED (fixed6), labelSexemodif, 32, 192);
  gtk_widget_set_size_request (labelSexemodif, 64, 16);

  radiobuttonHommemodif = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radiobuttonHommemodif);
  gtk_fixed_put (GTK_FIXED (fixed6), radiobuttonHommemodif, 144, 184);
  gtk_widget_set_size_request (radiobuttonHommemodif, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonHommemodif), radiobuttonHommemodif_group);
  radiobuttonHommemodif_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonHommemodif));

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_fixed_put (GTK_FIXED (fixed6), combobox2, 240, 144);
  gtk_widget_set_size_request (combobox2, 128, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Janvier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("F\303\251vrier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Mars"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Avril"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Mai"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Juin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Juillet"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Ao\303\273t"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Septembre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Octobre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Novembre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("D\303\251cembre"));

  radiobuttonFemmemodif = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radiobuttonFemmemodif);
  gtk_fixed_put (GTK_FIXED (fixed6), radiobuttonFemmemodif, 296, 184);
  gtk_widget_set_size_request (radiobuttonFemmemodif, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonFemmemodif), radiobuttonHommemodif_group);
  radiobuttonHommemodif_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonFemmemodif));

  labelEmailmodif = gtk_label_new (_("Email :"));
  gtk_widget_show (labelEmailmodif);
  gtk_fixed_put (GTK_FIXED (fixed6), labelEmailmodif, 64, 240);
  gtk_widget_set_size_request (labelEmailmodif, 49, 17);

  labelTelephonemodif = gtk_label_new (_("Telephone :"));
  gtk_widget_show (labelTelephonemodif);
  gtk_fixed_put (GTK_FIXED (fixed6), labelTelephonemodif, 48, 272);
  gtk_widget_set_size_request (labelTelephonemodif, 80, 16);

  labelVillemodif = gtk_label_new (_("mot de passe "));
  gtk_widget_show (labelVillemodif);
  gtk_fixed_put (GTK_FIXED (fixed6), labelVillemodif, 0, 312);
  gtk_widget_set_size_request (labelVillemodif, 121, 16);

  checkbutton2 = gtk_check_button_new_with_mnemonic (_("j'accepte la politique de confidentialit\303\251"));
  gtk_widget_show (checkbutton2);
  gtk_fixed_put (GTK_FIXED (fixed6), checkbutton2, 40, 344);
  gtk_widget_set_size_request (checkbutton2, 392, 32);

  labelModifier = gtk_label_new (_("Modifier"));
  gtk_widget_show (labelModifier);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), labelModifier);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed5);

  treeviewcitoyenC = gtk_tree_view_new ();
  gtk_widget_show (treeviewcitoyenC);
  gtk_fixed_put (GTK_FIXED (fixed5), treeviewcitoyenC, 24, 120);
  gtk_widget_set_size_request (treeviewcitoyenC, 712, 176);

  entryCINC = gtk_entry_new ();
  gtk_widget_show (entryCINC);
  gtk_fixed_put (GTK_FIXED (fixed5), entryCINC, 144, 72);
  gtk_widget_set_size_request (entryCINC, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryCINC), 8226);

  spinbuttonMoisC_adj = gtk_adjustment_new (2024, 2024, 2025, 1, 10, 10);
  spinbuttonMoisC = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonMoisC_adj), 1, 0);
  gtk_widget_show (spinbuttonMoisC);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbuttonMoisC, 504, 72);
  gtk_widget_set_size_request (spinbuttonMoisC, 72, 32);

  label59 = gtk_label_new (_("00.00  "));
  gtk_widget_show (label59);
  gtk_fixed_put (GTK_FIXED (fixed5), label59, 192, 352);
  gtk_widget_set_size_request (label59, 208, 40);

  labelCINC = gtk_label_new (_("CIN:"));
  gtk_widget_show (labelCINC);
  gtk_fixed_put (GTK_FIXED (fixed5), labelCINC, 152, 48);
  gtk_widget_set_size_request (labelCINC, 152, 16);

  label60 = gtk_label_new (_("mois"));
  gtk_widget_show (label60);
  gtk_fixed_put (GTK_FIXED (fixed5), label60, 392, 48);
  gtk_widget_set_size_request (label60, 49, 17);

  label61 = gtk_label_new (_("annee"));
  gtk_widget_show (label61);
  gtk_fixed_put (GTK_FIXED (fixed5), label61, 512, 48);
  gtk_widget_set_size_request (label61, 49, 17);

  buttonImprimer = gtk_button_new_with_mnemonic (_("calculer"));
  gtk_widget_show (buttonImprimer);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonImprimer, 608, 64);
  gtk_widget_set_size_request (buttonImprimer, 120, 40);

  combobox3 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox3);
  gtk_fixed_put (GTK_FIXED (fixed5), combobox3, 352, 72);
  gtk_widget_set_size_request (combobox3, 128, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Janvier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("F\303\251vrier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Mars"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Avril"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Mai"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Juin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Juillet"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Ao\303\273t"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Septembre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Octobre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Novembre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("D\303\251cembre"));

  labelcalculer = gtk_label_new (_("factures"));
  gtk_widget_show (labelcalculer);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), labelcalculer);

  g_signal_connect ((gpointer) buttonmodif, "clicked",
                    G_CALLBACK (on_buttonmodif_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonsupprimer, "clicked",
                    G_CALLBACK (on_buttonsupprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeviewcitoyenA, "row_activated",
                    G_CALLBACK (on_treeviewcitoyenA_row_activated),
                    NULL);
  g_signal_connect ((gpointer) recherchehome, "clicked",
                    G_CALLBACK (on_recherchehome_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonRafraichir, "clicked",
                    G_CALLBACK (on_buttonRafraichir_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonAjouter, "clicked",
                    G_CALLBACK (on_buttonAjouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) radioHommeA, "toggled",
                    G_CALLBACK (on_radioHommeA_toggled),
                    NULL);
  g_signal_connect ((gpointer) radioFemmeA, "toggled",
                    G_CALLBACK (on_radioFemmeA_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton1, "toggled",
                    G_CALLBACK (on_checkbutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) buttonModifier, "clicked",
                    G_CALLBACK (on_buttonModifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonHommemodif, "toggled",
                    G_CALLBACK (on_radiobuttonHommemodif_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonFemmemodif, "toggled",
                    G_CALLBACK (on_radiobuttonFemmemodif_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton2, "toggled",
                    G_CALLBACK (on_checkbutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) buttonImprimer, "clicked",
                    G_CALLBACK (on_buttonImprimer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestioncitoyen, gestioncitoyen, "gestioncitoyen");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, buttonmodif, "buttonmodif");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, image15, "image15");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label56, "label56");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, buttonsupprimer, "buttonsupprimer");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, image16, "image16");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label57, "label57");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, treeviewcitoyenA, "treeviewcitoyenA");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, entryrecherchehome, "entryrecherchehome");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, recherchehome, "recherchehome");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, image18, "image18");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, buttonRafraichir, "buttonRafraichir");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, image17, "image17");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label58, "label58");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, labelAfficher, "labelAfficher");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, entryNomA, "entryNomA");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, entryPrenomA, "entryPrenomA");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, spinbuttonJourA, "spinbuttonJourA");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, spinbuttonAnneeA, "spinbuttonAnneeA");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, entryVilleA, "entryVilleA");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, entryEmailA, "entryEmailA");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, entryCINA, "entryCINA");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, entryTelephoneA, "entryTelephoneA");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, labelPrenomA, "labelPrenomA");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, buttonAjouter, "buttonAjouter");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, image7, "image7");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label, "label");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, labelEmailA, "labelEmailA");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, labelTelephoneA, "labelTelephoneA");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, labelVilleA, "labelVilleA");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, labelSexeA, "labelSexeA");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, labelDatenaissanceA, "labelDatenaissanceA");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, radioHommeA, "radioHommeA");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, radioFemmeA, "radioFemmeA");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, labelNomA, "labelNomA");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, labelCINA, "labelCINA");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, labelAjouter, "labelAjouter");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, entryNommodif, "entryNommodif");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, entryPrenommodif, "entryPrenommodif");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, spinbuttonJourmodif, "spinbuttonJourmodif");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, entryEmailmodif, "entryEmailmodif");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, entryCINmodif, "entryCINmodif");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, entryTelephonemodif, "entryTelephonemodif");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, entryVillemodif, "entryVillemodif");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, spinbuttonAnneemodif, "spinbuttonAnneemodif");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, labelPrenommodif, "labelPrenommodif");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, labelNommodif, "labelNommodif");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, labelCINconf, "labelCINconf");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, buttonModifier, "buttonModifier");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, image12, "image12");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label52, "label52");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, labelDatenaissancemodif, "labelDatenaissancemodif");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, labelSexemodif, "labelSexemodif");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, radiobuttonHommemodif, "radiobuttonHommemodif");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, combobox2, "combobox2");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, radiobuttonFemmemodif, "radiobuttonFemmemodif");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, labelEmailmodif, "labelEmailmodif");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, labelTelephonemodif, "labelTelephonemodif");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, labelVillemodif, "labelVillemodif");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, labelModifier, "labelModifier");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, treeviewcitoyenC, "treeviewcitoyenC");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, entryCINC, "entryCINC");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, spinbuttonMoisC, "spinbuttonMoisC");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label59, "label59");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, labelCINC, "labelCINC");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label60, "label60");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label61, "label61");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, buttonImprimer, "buttonImprimer");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, combobox3, "combobox3");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, labelcalculer, "labelcalculer");

  return gestioncitoyen;
}

